{% set name = "wannier90" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wannier-developers/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3700372489435fc3165b2b213c22708cc947babd96e652641fad84240191c1dd

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - make
  host:
    - libblas
    - liblapack
  run:

test:
  commands:
    - test -f ${PREFIX}/bin/wannier90.x
    - test -f ${PREFIX}/bin/postw90.x

about:
  home: http://www.wannier.org/
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'The Maximally-Localised Generalised Wannier Functions Code'

  description: |
    Wannier90 is an open-source code (released under GPLv2) for 
    generating maximally-localized Wannier functions and using them
    to compute advanced electronic properties of materials with high 
    efficiency and accuracy.    
  doc_url: https://github.com/wannier-developers/wannier90/tree/master/doc
  dev_url: https://github.com/wannier-developers/wannier90

extra:
  recipe-maintainers:
    - edan-bainglass
    - jan-janssen
    - mbercx
